updated file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,7 +94,6 @@ jobs:
 
       - name: Start android emulator and run test
         uses: reactivecircus/android-emulator-runner@v2
-        timeout-minutes: 30
         with: 
           api-level: 34
           arch: x86_64
@@ -104,10 +103,15 @@ jobs:
             adb shell getprop initsvc.bootmain
             adb devices
 
+            echo "Downloading Appium setting APK"
+            curl -L -o settings_apk-debug.apk https://github.com/appium-uiautomator2-driver/releases/download/v7.2.3/settings_apk-debug.apk
+            echo "Downloading UiAutomator2 Server APK"
+            curl -L -o appium-uiautomator-server-v7.2.3.apk https://github.com/appium-uiautomator2-driver/releases/download/v7.2.3/appium-uiautomator2-server-v7.2.3.apk
+
             echo "Installing Appium settings APK"
-            adb install ./node_modules/appium-uiautomator2-driver/apks/settings_apk_debug.apk || echo "Failed to install setting apk"
+            adb install ./settings_apk_debug.apk || echo "Failed to install setting apk"
             echo "Installing UiAutomator2 server APK"
-            adb install ./node_modules/appium-uiautomator2-driver/apks/appium-uiautomator2-server-v7.2.3.apk || echo "Failed to install UiAutomator2 Server APK"
+            adb install ./appium-uiautomator2-server-v7.2.3.apk || echo "Failed to install UiAutomator2 Server APK"
 
             echo "Granting necessary permissions..."
             adb shell pm grant io.appium.android.setting android.permissions.SETTINGS
