updated file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -108,10 +108,14 @@ jobs:
             echo "Downloading UiAutomator2 Server APK"
             curl -L -o appium-uiautomator-server-v7.2.3.apk https://github.com/appium-uiautomator2-driver/releases/download/v7.2.3/appium-uiautomator2-server-v7.2.3.apk
 
+            echo "Current directory is: $(pwd)"
+            echo "List files in current directory"
+            ls -l
+
             echo "Installing Appium settings APK"
-            adb install ./settings_apk_debug.apk || echo "Failed to install setting apk"
+            adb install $(pwd)/settings_apk_debug.apk || echo "Failed to install setting apk"
             echo "Installing UiAutomator2 server APK"
-            adb install ./appium-uiautomator2-server-v7.2.3.apk || echo "Failed to install UiAutomator2 Server APK"
+            adb install $(pwd)/appium-uiautomator2-server-v7.2.3.apk || echo "Failed to install UiAutomator2 Server APK"
 
             echo "Granting necessary permissions..."
             adb shell pm grant io.appium.android.setting android.permissions.SETTINGS
