updated file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,16 +106,30 @@ jobs:
           disable-animations: true
           emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -no-snapshot -tcpdump tcpdump.pcap"
           script: |
-            echo "Waiting for emulator to boot"
-            adb wait-for-device
-            adb shell input keyevent 82
-            echo "emulator booted"
-            while true; do sleep 60; done
+            echo "Starting emulator"
+            adb devices
+            adb wait-for-devices || echo "ADB failed to detect the device"
+            adb shell getprop init.svc.bootanim || echo "Boot animation status not found"
+            adb shell input keyevent 82 || echo "Failed to send key event"
+            adb shell dumpsys power || echo "Power service is not available"
+            adb logcat -d -b main -b systems -b crash || echo "No logcats logs found"
+            echo "Emulator should be running now"
+            adb devices
+
+      - name: Start Emulator manually
+        if: failure()
+        run: |
+          echo "android-emulator-runner failed, starting emulator manually"
+          nohup $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_34 -no-window -no-audio -no-boot-anim -gpu switfshader_indirect -no-snapshot > emulator.log 2>&1 &
+          sleep 60
+          adb devices
+          adb shell getprop init.svc.bootanim   
         
       - name: Check emulator Status
         run: |
-          echo "Waiting for emulator to boot..."
+          echo "Checking if emulator is running..."
           adb devices
+          adb shell getprop init.svc.bootanim
             
       - name: List installed Appium drivers
         run: appium driver list --installed
